name: BuildAndTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Init database
        run: |
          mysql --host 127.0.0.1 --port 4000 -u root << EOF
          use test;
          create table X(id int, a int);
          EOF
      - name: Run example
        run: RUST_LOG=debug cargo run -- -u mysql://root@127.0.0.1:4000/test asset/a.sql asset/b.sql
    
    services:
      tidb:
        image: pingcap/tidb
        ports:
          - 4000:4000
          - 10080:10080
        volumes:
          - /etc/localtime:/etc/localtime
